'use client'

import { useState, useEffect, useRef } from 'react'
import { FileDown, Plus, Trash2, ChevronUp, ChevronDown, Printer, X } from 'lucide-react'
import TerminalCard from '@/components/ui/TerminalCard'
import { clsx } from 'clsx'

// ─── Types ────────────────────────────────────────────────────────────────────
type Classification = 'PUBLIC' | 'INTERNAL' | 'CONFIDENTIAL' | 'RESTRICTED'
type Severity       = 'critical' | 'high' | 'medium' | 'low' | 'info'
type IocType        = 'IP' | 'Domain' | 'URL' | 'MD5' | 'SHA256' | 'Email' | 'File Path' | 'Other'

interface ReportMeta {
  title: string; target: string; analyst: string
  date: string; classification: Classification; summary: string
}

interface FindingSection { type: 'finding'; id: string; severity: Severity; title: string; description: string; recommendation: string; cvss: string }
interface IocSection     { type: 'ioc';     id: string; iocType: IocType;  value: string; confidence: string; source: string; description: string }
interface TextSection    { type: 'text';    id: string; heading: string;   content: string }
interface RawSection     { type: 'raw';     id: string; tool: string;      content: string }
type Section = FindingSection | IocSection | TextSection | RawSection

const DRAFT_KEY = 'cyberops_report_draft'
const TODAY     = new Date().toISOString().slice(0, 10)

function uid() { return Math.random().toString(36).slice(2, 10) }

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

// ─── Markdown generator ───────────────────────────────────────────────────────
function toMarkdown(meta: ReportMeta, sections: Section[]): string {
  const lines: string[] = [
    `# ${meta.title || 'Security Report'}`, '',
    `| Field | Value |`, `|---|---|`,
    `| **Target** | \`${meta.target || '—'}\` |`,
    `| **Analyst** | ${meta.analyst || '—'} |`,
    `| **Date** | ${meta.date} |`,
    `| **Classification** | ${meta.classification} |`, '',
  ]
  if (meta.summary) lines.push(`## Executive Summary`, '', meta.summary, '')

  const sevIcon: Record<Severity, string> = { critical: '🔴', high: '🟠', medium: '🟡', low: '🔵', info: '⚪' }

  for (const s of sections) {
    if (s.type === 'finding') {
      lines.push(`## ${sevIcon[s.severity]} [${s.severity.toUpperCase()}] ${s.title || 'Untitled Finding'}`, '')
      if (s.cvss) lines.push(`**CVSS:** \`${s.cvss}\`  `)
      lines.push(s.description || '_No description._', '')
      if (s.recommendation) lines.push(`### Recommendation`, '', s.recommendation, '')
    } else if (s.type === 'ioc') {
      lines.push(`## IOC: \`${s.value || '—'}\``, '',
        `- **Type:** ${s.iocType}`,
        `- **Confidence:** ${s.confidence}`,
        `- **Source:** ${s.source || '—'}`,
        '', s.description || '', '')
    } else if (s.type === 'text') {
      if (s.heading) lines.push(`## ${s.heading}`, '')
      lines.push(s.content || '', '')
    } else if (s.type === 'raw') {
      if (s.tool) lines.push(`## Tool Output: ${s.tool}`, '')
      lines.push('```', s.content || '', '```', '')
    }
  }

  lines.push('---', `_Generated by CyberOps Dashboard · ${new Date().toISOString()}_`)
  return lines.join('\n')
}

// ─── PDF HTML builder ─────────────────────────────────────────────────────────
function toPrintHtml(meta: ReportMeta, sections: Section[]): string {
  const sevColor: Record<Severity, string> = {
    critical: '#dc2626', high: '#ea580c', medium: '#d97706', low: '#2563eb', info: '#6b7280',
  }
  const sevBg: Record<Severity, string> = {
    critical: '#fef2f2', high: '#fff7ed', medium: '#fffbeb', low: '#eff6ff', info: '#f9fafb',
  }

  let body = `
    <h1>${esc(meta.title || 'Security Report')}</h1>
    <table class="meta">
      <tr><td>Target</td><td><code>${esc(meta.target || '—')}</code></td></tr>
      <tr><td>Analyst</td><td>${esc(meta.analyst || '—')}</td></tr>
      <tr><td>Date</td><td>${esc(meta.date)}</td></tr>
      <tr><td>Classification</td><td><strong>${esc(meta.classification)}</strong></td></tr>
    </table>`

  if (meta.summary) body += `<h2>Executive Summary</h2><p>${esc(meta.summary).replace(/\n/g, '<br>')}</p>`

  for (const s of sections) {
    if (s.type === 'finding') {
      const c = sevColor[s.severity], bg = sevBg[s.severity]
      body += `
        <div style="border-left:4px solid ${c};padding:0.5em 1em;margin:1.5em 0;background:${bg}11">
          <h2 style="margin-top:0">${esc(s.title || 'Untitled Finding')}
            <span style="font-size:0.65em;background:${bg};color:${c};padding:2px 10px;border-radius:4px;text-transform:uppercase;vertical-align:middle;margin-left:8px">${s.severity}</span>
            ${s.cvss ? `<span style="font-size:0.65em;color:#6b7280;margin-left:4px">CVSS ${esc(s.cvss)}</span>` : ''}
          </h2>
          <p>${esc(s.description || '').replace(/\n/g, '<br>')}</p>
          ${s.recommendation ? `<h3 style="color:#374151">Recommendation</h3><p>${esc(s.recommendation).replace(/\n/g, '<br>')}</p>` : ''}
        </div>`
    } else if (s.type === 'ioc') {
      body += `
        <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:0.75em 1em;margin:1.5em 0;font-family:monospace">
          <strong style="font-size:1.05em">${esc(s.value || '—')}</strong>
          <span style="color:#6b7280;margin-left:8px">${esc(s.iocType)}</span>
          <span style="color:#6b7280;margin-left:8px">· Confidence: ${esc(s.confidence)}</span>
          ${s.source ? `<span style="color:#6b7280;margin-left:8px">· Source: ${esc(s.source)}</span>` : ''}
          ${s.description ? `<p style="font-family:sans-serif;color:#374151;margin-top:0.5em">${esc(s.description).replace(/\n/g, '<br>')}</p>` : ''}
        </div>`
    } else if (s.type === 'text') {
      body += `${s.heading ? `<h2>${esc(s.heading)}</h2>` : ''}<p>${esc(s.content || '').replace(/\n/g, '<br>')}</p>`
    } else if (s.type === 'raw') {
      body += `${s.tool ? `<h2>Tool Output: ${esc(s.tool)}</h2>` : ''}
        <pre>${esc(s.content || '')}</pre>`
    }
  }

  return `<!DOCTYPE html><html><head><meta charset="utf-8">
  <title>${esc(meta.title || 'Security Report')}</title>
  <style>
    *{box-sizing:border-box}body{font-family:Georgia,serif;max-width:900px;margin:40px auto;color:#111;line-height:1.65}
    h1{border-bottom:3px solid #111;padding-bottom:.4em}h2{border-bottom:1px solid #e5e7eb;padding-bottom:.2em;margin-top:2em}
    table.meta{border-collapse:collapse;margin-bottom:2em}table.meta td{padding:6px 14px;border:1px solid #e5e7eb}
    table.meta td:first-child{font-weight:bold;background:#f9fafb;white-space:nowrap}
    pre{background:#f1f5f9;padding:1em;border-radius:6px;overflow:auto;white-space:pre-wrap;font-size:.85em}
    code{background:#f1f5f9;padding:1px 6px;border-radius:3px}
    hr{border:none;border-top:1px solid #e5e7eb;margin-top:3em}
    @media print{body{margin:0}@page{margin:1.5cm}}
  </style></head><body>${body}
  <hr><p style="color:#9ca3af;font-size:.8em">Generated by CyberOps Dashboard · ${new Date().toISOString()}</p>
  </body></html>`
}

// ─── Severity + section helpers ───────────────────────────────────────────────
const SEV_COLORS: Record<Severity, string> = {
  critical: 'text-cyber-red border-cyber-red/30',
  high:     'text-cyber-orange border-cyber-orange/30',
  medium:   'text-yellow-400 border-yellow-400/30',
  low:      'text-cyber-cyan border-cyber-cyan/30',
  info:     'text-cyber-muted border-cyber-border/60',
}

const SECTION_LABELS: Record<Section['type'], string> = {
  finding: 'Finding', ioc: 'IOC', text: 'Text Block', raw: 'Raw Output',
}

// ─── Section form components ──────────────────────────────────────────────────
function FindingForm({ s, upd }: { s: FindingSection; upd: (p: Partial<FindingSection>) => void }) {
  return (
    <div className="space-y-2.5">
      <div className="grid grid-cols-2 gap-2">
        <div>
          <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Severity</label>
          <select value={s.severity} onChange={e => upd({ severity: e.target.value as Severity })}
            className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi focus:outline-none focus:border-cyber-cyan/40">
            {(['critical','high','medium','low','info'] as Severity[]).map(v => <option key={v} value={v}>{v.charAt(0).toUpperCase()+v.slice(1)}</option>)}
          </select>
        </div>
        <div>
          <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">CVSS Score</label>
          <input value={s.cvss} onChange={e => upd({ cvss: e.target.value })} placeholder="e.g. 9.8"
            className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
        </div>
      </div>
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Title</label>
        <input value={s.title} onChange={e => upd({ title: e.target.value })} placeholder="Vulnerability title"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
      </div>
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Description</label>
        <textarea value={s.description} onChange={e => upd({ description: e.target.value })} rows={3} placeholder="Detailed description of the finding…"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40 resize-y" />
      </div>
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Recommendation</label>
        <textarea value={s.recommendation} onChange={e => upd({ recommendation: e.target.value })} rows={2} placeholder="Remediation steps…"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40 resize-y" />
      </div>
    </div>
  )
}

function IocForm({ s, upd }: { s: IocSection; upd: (p: Partial<IocSection>) => void }) {
  return (
    <div className="space-y-2.5">
      <div className="grid grid-cols-3 gap-2">
        <div>
          <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Type</label>
          <select value={s.iocType} onChange={e => upd({ iocType: e.target.value as IocType })}
            className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi focus:outline-none focus:border-cyber-cyan/40">
            {(['IP','Domain','URL','MD5','SHA256','Email','File Path','Other'] as IocType[]).map(v => <option key={v} value={v}>{v}</option>)}
          </select>
        </div>
        <div className="col-span-2">
          <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Value</label>
          <input value={s.value} onChange={e => upd({ value: e.target.value })} placeholder="IOC value"
            className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-2">
        <div>
          <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Confidence</label>
          <select value={s.confidence} onChange={e => upd({ confidence: e.target.value })}
            className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi focus:outline-none focus:border-cyber-cyan/40">
            {['high','medium','low'].map(v => <option key={v} value={v}>{v.charAt(0).toUpperCase()+v.slice(1)}</option>)}
          </select>
        </div>
        <div>
          <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Source / Tool</label>
          <input value={s.source} onChange={e => upd({ source: e.target.value })} placeholder="e.g. ThreatFox"
            className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
        </div>
      </div>
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Context / Notes</label>
        <textarea value={s.description} onChange={e => upd({ description: e.target.value })} rows={2} placeholder="Context about this IOC…"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40 resize-y" />
      </div>
    </div>
  )
}

function TextForm({ s, upd }: { s: TextSection; upd: (p: Partial<TextSection>) => void }) {
  return (
    <div className="space-y-2.5">
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Heading (optional)</label>
        <input value={s.heading} onChange={e => upd({ heading: e.target.value })} placeholder="Section heading"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
      </div>
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Content (Markdown supported)</label>
        <textarea value={s.content} onChange={e => upd({ content: e.target.value })} rows={5} placeholder="Free-text content…"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40 resize-y" />
      </div>
    </div>
  )
}

function RawForm({ s, upd }: { s: RawSection; upd: (p: Partial<RawSection>) => void }) {
  return (
    <div className="space-y-2.5">
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Tool / Source Name</label>
        <input value={s.tool} onChange={e => upd({ tool: e.target.value })} placeholder="e.g. Nmap, Auto Scanner"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
      </div>
      <div>
        <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Raw Output (paste here)</label>
        <textarea value={s.content} onChange={e => upd({ content: e.target.value })} rows={6} placeholder="Paste tool output or JSON results…"
          className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-2 py-1.5 font-mono text-[10px] text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40 resize-y" />
      </div>
    </div>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────
const DEFAULT_META: ReportMeta = { title: '', target: '', analyst: '', date: TODAY, classification: 'CONFIDENTIAL', summary: '' }

export default function ExportPage() {
  const [meta, setMeta]         = useState<ReportMeta>(DEFAULT_META)
  const [sections, setSections] = useState<Section[]>([])
  const [showAdd, setShowAdd]   = useState(false)
  const addRef                  = useRef<HTMLDivElement>(null)

  // Load draft
  useEffect(() => {
    try {
      const raw = localStorage.getItem(DRAFT_KEY)
      if (raw) { const d = JSON.parse(raw); setMeta(d.meta ?? DEFAULT_META); setSections(d.sections ?? []) }
    } catch {}
  }, [])

  // Auto-save draft
  useEffect(() => {
    const t = setTimeout(() => {
      try { localStorage.setItem(DRAFT_KEY, JSON.stringify({ meta, sections })) } catch {}
    }, 600)
    return () => clearTimeout(t)
  }, [meta, sections])

  function upMeta<K extends keyof ReportMeta>(k: K, v: ReportMeta[K]) { setMeta(p => ({ ...p, [k]: v })) }

  function addSection(type: Section['type']) {
    const id = uid()
    const s: Section = type === 'finding' ? { type, id, severity: 'high', title: '', description: '', recommendation: '', cvss: '' }
                     : type === 'ioc'     ? { type, id, iocType: 'IP', value: '', confidence: 'high', source: '', description: '' }
                     : type === 'text'    ? { type, id, heading: '', content: '' }
                     :                     { type, id, tool: '', content: '' }
    setSections(p => [...p, s])
    setShowAdd(false)
  }

  function upSection(id: string, updates: object) {
    setSections(p => p.map(s => s.id === id ? { ...s, ...updates } : s))
  }

  function delSection(id: string) { setSections(p => p.filter(s => s.id !== id)) }

  function move(id: string, dir: -1 | 1) {
    setSections(p => {
      const i = p.findIndex(s => s.id === id)
      if (i + dir < 0 || i + dir >= p.length) return p
      const n = [...p]; [n[i], n[i + dir]] = [n[i + dir], n[i]]; return n
    })
  }

  function downloadMarkdown() {
    const md   = toMarkdown(meta, sections)
    const blob = new Blob([md], { type: 'text/markdown' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = (meta.title || 'report').replace(/\s+/g, '_') + '.md'
    a.click(); URL.revokeObjectURL(url)
  }

  function printPdf() {
    const html = toPrintHtml(meta, sections)
    const win  = window.open('', '_blank', 'width=960,height=720,noopener')
    if (!win) { alert('Allow popups in your browser to use PDF export.'); return }
    win.document.open(); win.document.write(html); win.document.close()
    setTimeout(() => { win.focus(); win.print() }, 400)
  }

  function clearDraft() {
    setMeta(DEFAULT_META); setSections([])
    try { localStorage.removeItem(DRAFT_KEY) } catch {}
  }

  const sectionCount = { finding: sections.filter(s => s.type === 'finding').length, ioc: sections.filter(s => s.type === 'ioc').length }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-4">
          <div className="w-10 h-10 rounded border border-cyber-cyan/30 flex items-center justify-center bg-cyber-cyan/5 flex-none">
            <FileDown size={18} className="text-cyber-cyan" />
          </div>
          <div>
            <h1 className="font-mono text-lg font-semibold text-cyber-text-hi">Report Builder</h1>
            <p className="font-mono text-xs text-cyber-muted mt-0.5">
              Compose findings, IOCs and tool output into a structured report. Export as Markdown or PDF. Draft auto-saved locally.
            </p>
          </div>
        </div>
        <button onClick={clearDraft} className="font-mono text-[10px] text-cyber-muted hover:text-cyber-red transition-colors whitespace-nowrap border border-cyber-border/40 hover:border-cyber-red/30 rounded px-2.5 py-1.5">
          Clear draft
        </button>
      </div>

      {/* Report metadata */}
      <TerminalCard title="Report Metadata" label="META" accent="cyan">
        <div className="grid grid-cols-2 gap-3">
          <div className="col-span-2">
            <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Report Title</label>
            <input value={meta.title} onChange={e => upMeta('title', e.target.value)} placeholder="e.g. Web Application Penetration Test — ACME Corp"
              className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-3 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
          </div>
          {([
            { k: 'target' as const,  label: 'Target',      ph: 'domain.com or 10.0.0.0/24' },
            { k: 'analyst' as const, label: 'Analyst',     ph: 'Your name or handle' },
            { k: 'date' as const,    label: 'Date',        ph: TODAY, type: 'date' },
          ]).map(({ k, label, ph, type }) => (
            <div key={k}>
              <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">{label}</label>
              <input type={type ?? 'text'} value={meta[k]} onChange={e => upMeta(k, e.target.value)} placeholder={ph}
                className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-3 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40" />
            </div>
          ))}
          <div>
            <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Classification</label>
            <select value={meta.classification} onChange={e => upMeta('classification', e.target.value as Classification)}
              className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-3 py-1.5 font-mono text-xs text-cyber-text-hi focus:outline-none focus:border-cyber-cyan/40">
              {(['PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED'] as Classification[]).map(v => <option key={v} value={v}>{v}</option>)}
            </select>
          </div>
          <div className="col-span-2">
            <label className="font-mono text-[9px] text-cyber-muted uppercase tracking-widest">Executive Summary (optional)</label>
            <textarea value={meta.summary} onChange={e => upMeta('summary', e.target.value)} rows={3} placeholder="Brief summary for management…"
              className="w-full mt-0.5 bg-cyber-bg border border-cyber-border rounded px-3 py-1.5 font-mono text-xs text-cyber-text-hi placeholder:text-cyber-muted focus:outline-none focus:border-cyber-cyan/40 resize-y" />
          </div>
        </div>
      </TerminalCard>

      {/* Section list */}
      <div className="space-y-3">
        {sections.map((s, idx) => {
          const typeLabel  = SECTION_LABELS[s.type]
          const sTitle     = s.type === 'finding' ? s.title || 'Untitled Finding'
                           : s.type === 'ioc'     ? s.value || 'IOC'
                           : s.type === 'text'    ? s.heading || 'Text Block'
                           : s.tool || 'Raw Output'
          return (
            <TerminalCard key={s.id} accent={s.type === 'finding' ? 'red' : s.type === 'ioc' ? 'orange' : 'none'}>
              {/* Section header */}
              <div className="flex items-center gap-2 mb-3">
                <span className={clsx('font-mono text-[9px] border rounded px-1.5 py-0.5 flex-none', {
                  'text-cyber-red border-cyber-red/30':    s.type === 'finding',
                  'text-cyber-orange border-cyber-orange/30': s.type === 'ioc',
                  'text-cyber-cyan border-cyber-cyan/30':  s.type === 'text',
                  'text-cyber-muted border-cyber-border/60': s.type === 'raw',
                })}>
                  {typeLabel}
                </span>
                {s.type === 'finding' && (
                  <span className={clsx('font-mono text-[9px] border rounded px-1.5 py-0.5', SEV_COLORS[s.severity])}>
                    {s.severity}
                  </span>
                )}
                <span className="font-mono text-xs text-cyber-text-hi flex-1 truncate">{sTitle}</span>
                <div className="flex items-center gap-1 flex-none">
                  <button onClick={() => move(s.id, -1)} disabled={idx === 0} className="text-cyber-muted hover:text-cyber-cyan disabled:opacity-30 transition-colors p-0.5"><ChevronUp size={12} /></button>
                  <button onClick={() => move(s.id, 1)} disabled={idx === sections.length - 1} className="text-cyber-muted hover:text-cyber-cyan disabled:opacity-30 transition-colors p-0.5"><ChevronDown size={12} /></button>
                  <button onClick={() => delSection(s.id)} className="text-cyber-muted hover:text-cyber-red transition-colors p-0.5 ml-1"><Trash2 size={12} /></button>
                </div>
              </div>
              {/* Section form */}
              {s.type === 'finding' && <FindingForm s={s} upd={u => upSection(s.id, u)} />}
              {s.type === 'ioc'     && <IocForm     s={s} upd={u => upSection(s.id, u)} />}
              {s.type === 'text'    && <TextForm    s={s} upd={u => upSection(s.id, u)} />}
              {s.type === 'raw'     && <RawForm     s={s} upd={u => upSection(s.id, u)} />}
            </TerminalCard>
          )
        })}
      </div>

      {/* Add section */}
      <div className="relative" ref={addRef}>
        <button
          onClick={() => setShowAdd(v => !v)}
          className="flex items-center gap-2 font-mono text-xs text-cyber-muted hover:text-cyber-cyan border border-dashed border-cyber-border/60 hover:border-cyber-cyan/40 rounded px-4 py-2.5 w-full justify-center transition-all"
        >
          <Plus size={13} /> Add Section
        </button>
        {showAdd && (
          <div className="absolute top-full left-0 mt-1 z-20 bg-cyber-card border border-cyber-border rounded-md shadow-lg flex gap-0 overflow-hidden">
            {(['finding','ioc','text','raw'] as Section['type'][]).map(t => (
              <button key={t} onClick={() => addSection(t)}
                className="px-4 py-2.5 font-mono text-xs text-cyber-muted hover:text-cyber-cyan hover:bg-cyber-surface/60 transition-colors border-r border-cyber-border last:border-0 whitespace-nowrap">
                {SECTION_LABELS[t]}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Export bar */}
      <TerminalCard title="Export" label="OUTPUT" accent="none">
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3 flex-wrap text-[10px] font-mono text-cyber-muted">
            <span>{sections.length} section{sections.length !== 1 ? 's' : ''}</span>
            {sectionCount.finding > 0 && <span className="text-cyber-red">{sectionCount.finding} finding{sectionCount.finding !== 1 ? 's' : ''}</span>}
            {sectionCount.ioc > 0     && <span className="text-cyber-orange">{sectionCount.ioc} IOC{sectionCount.ioc !== 1 ? 's' : ''}</span>}
          </div>
          <div className="flex gap-2">
            <button onClick={downloadMarkdown}
              className="flex items-center gap-2 px-4 py-2 bg-cyber-cyan/10 border border-cyber-cyan/30 text-cyber-cyan font-mono text-xs rounded hover:bg-cyber-cyan/20 transition-all">
              <FileDown size={12} /> Markdown
            </button>
            <button onClick={printPdf}
              className="flex items-center gap-2 px-4 py-2 bg-cyber-surface border border-cyber-border text-cyber-text font-mono text-xs rounded hover:border-cyber-cyan/30 hover:text-cyber-cyan transition-all">
              <Printer size={12} /> PDF / Print
            </button>
          </div>
        </div>
        <p className="font-mono text-[9px] text-cyber-muted mt-2">
          PDF export opens a print dialog in a new window — enable popups if blocked. Markdown downloads as <code className="text-cyber-cyan">.md</code>.
        </p>
      </TerminalCard>
    </div>
  )
}
